//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalif
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Type
    {
        public int Id { get; set; }
        public int Type_material { get; set; }
        public decimal Brak { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
