//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalif
{
    using System;
    using System.Collections.Generic;

    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        public int OrderID { get; set; }
        public int TableID { get; set; }
        public int WaiterID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal TotalSum { get; set; }
        public string Status { get; set; }

        public virtual Tables Tables { get; set; } // Навигационное свойство
        public virtual Users Users { get; set; }   // Навигационное свойство
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
