//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalif
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Name_Partner { get; set; }
        public int Quatity_Product { get; set; }
        public System.DateTime Date_Sale { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Partners Partners { get; set; }
    }
}
